# Reports bundle size changes in pull requests.
# To find the report:
# 1. Go to the PR page
# 2. Click on the "Checks" tab
# 3. Click on the "Size" workflow
# 4. The bundle size report will be shown at the top of the job summary

name: Size

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

permissions:
  contents: read
jobs:
  size:
    name: Report bundle size
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies (base)
        run: bun install

      - name: Build (base)
        run: bun run build

      - name: Get base bundle size breakdown
        id: base-size
        run: |
          echo "total=$(du -sh dist | cut -f1)" >> $GITHUB_OUTPUT
          echo "breakdown<<EOF" >> $GITHUB_OUTPUT
          find dist -type f -name "*.js" -o -name "*.css" | while read file; do
            echo "$(du -sh $file | cut -f1) - $(basename $file)"
          done >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Install dependencies (PR)
        run: bun install

      - name: Build (PR)
        run: bun run build

      - name: Get PR bundle size breakdown
        id: pr-size
        run: |
          echo "total=$(du -sh dist | cut -f1)" >> $GITHUB_OUTPUT
          echo "breakdown<<EOF" >> $GITHUB_OUTPUT
          find dist -type f -name "*.js" -o -name "*.css" | while read file; do
            echo "$(du -sh $file | cut -f1) - $(basename $file)"
          done >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Calculate size difference
        id: size-diff
        run: |
          base_size=$(echo ${{ steps.base-size.outputs.total }} | sed 's/[^0-9.]*//g')
          pr_size=$(echo ${{ steps.pr-size.outputs.total }} | sed 's/[^0-9.]*//g')
          diff=$(echo "$pr_size - $base_size" | bc)
          if (( $(echo "$diff > 0" | bc -l) )); then
            echo "total=+$diff" >> $GITHUB_OUTPUT
          else
            echo "total=$diff" >> $GITHUB_OUTPUT
          fi

      - name: Generate Bundle Size Report
        run: |
          # Write to job summary
          echo "## Bundle Size Report" >> $GITHUB_STEP_SUMMARY
          echo "### Total Size" >> $GITHUB_STEP_SUMMARY
          echo "- Base branch: ${{ steps.base-size.outputs.total }}" >> $GITHUB_STEP_SUMMARY
          echo "- PR branch: ${{ steps.pr-size.outputs.total }}" >> $GITHUB_STEP_SUMMARY
          echo "- Difference: ${{ steps.size-diff.outputs.total }}MB" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Base Branch Breakdown" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.base-size.outputs.breakdown }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### PR Branch Breakdown" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.pr-size.outputs.breakdown }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

          # Also echo to logs for immediate visibility
          echo "=============== BUNDLE SIZE REPORT ==============="
          echo "Total Size:"
          echo "- Base branch: ${{ steps.base-size.outputs.total }}"
          echo "- PR branch: ${{ steps.pr-size.outputs.total }}"
          echo "- Difference: ${{ steps.size-diff.outputs.total }}MB"
          echo ""
          echo "Base Branch Breakdown:"
          echo "${{ steps.base-size.outputs.breakdown }}"
          echo ""
          echo "PR Branch Breakdown:"
          echo "${{ steps.pr-size.outputs.breakdown }}"
          echo "================================================" 