# Reports bundle size changes in pull requests.
# To find the report:
# 1. Go to the PR page
# 2. Click on the "Checks" tab
# 3. Click on the "Size" workflow
# 4. The bundle size report will be shown at the top of the job summary

name: Bundle Size Report

on:
  workflow_run:
    workflows: ["Trigger Size Check"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v3

      - name: Get PR number
        uses: potiuk/get-workflow-origin@v1_5
        id: workflow-origin
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: bundle-stats
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build base stats
        run: |
          VITE_BUNDLE_ANALYZE=true bun run build --mode production
          mv dist/stats.html dist/base-stats.html

      - name: Generate Bundle Size Report
        id: report
        run: |
          echo "report<<EOF" >> $GITHUB_OUTPUT
          echo "## 📦 Bundle Size Analysis" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "### Base Branch Stats" >> $GITHUB_OUTPUT
          cat dist/base-stats.html | grep -A 50 "<pre>" | grep -B 50 "</pre>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "### PR Branch Stats" >> $GITHUB_OUTPUT
          cat stats.html | grep -A 50 "<pre>" | grep -B 50 "</pre>" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ steps.workflow-origin.outputs.pull_request_number }}
          comment-author: 'github-actions[bot]'
          body-includes: '## 📦 Bundle Size Report'

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.workflow-origin.outputs.pull_request_number }}
          body: ${{ steps.report.outputs.report }}
          edit-mode: replace