# Reports bundle size changes in pull requests.
# To find the report:
# 1. Go to the PR page
# 2. Click on the "Checks" tab
# 3. Click on the "Size" workflow
# 4. The bundle size report will be shown at the top of the job summary

name: Size

# Change trigger to workflow_dispatch
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
      base_ref:
        description: 'Base Branch Reference'
        required: true
      head_ref:
        description: 'Head Branch Reference'
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  size:
    name: Report bundle size
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.base_ref }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies (base)
        run: bun install

      - name: Build with stats (base)
        run: |
          VITE_BUNDLE_ANALYZE=true bun run build --mode production
          mv dist/stats.html dist/base-stats.html

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.head_ref }}

      - name: Install dependencies (PR)
        run: bun install

      - name: Build with stats (PR)
        run: |
          VITE_BUNDLE_ANALYZE=true bun run build --mode production

      - name: Generate Bundle Size Report
        id: report
        run: |
          echo "report<<EOF" >> $GITHUB_OUTPUT
          echo "## 📦 Bundle Size Analysis" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "### Base Branch Stats" >> $GITHUB_OUTPUT
          cat dist/base-stats.html | grep -A 50 "<pre>" | grep -B 50 "</pre>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "### PR Branch Stats" >> $GITHUB_OUTPUT
          cat dist/stats.html | grep -A 50 "<pre>" | grep -B 50 "</pre>" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.inputs.pr_number }}
          comment-author: 'github-actions[bot]'
          body-includes: '## 📦 Bundle Size Report'

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.inputs.pr_number }}
          body: ${{ steps.report.outputs.report }}
          edit-mode: replace 