name: Trigger Size Check

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'package.json'
      - 'vite.config.ts'
      - 'bun.lockb'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build with stats
        run: |
          VITE_BUNDLE_ANALYZE=true bun run build --mode production

      - name: Upload stats
        uses: actions/upload-artifact@v4
        with:
          name: bundle-stats
          path: dist/stats.html